include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/generated/**

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    unnecessary_lambdas: true
    prefer_expression_function_bodies: true
    lines_longer_than_80_chars: true
  

