workflows:
  android-staging:
    name: Android Staging APK
    instance_type: mac_mini_m2
    max_build_duration: 61

    environment:
      flutter: stable
      groups:
        - env_vars
      android_signing:
        - debug.keystore.android

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'staging'
          include: true

    cache:
      cache_paths:
        - $HOME/.pub-cache

    scripts:
      - name: Decode google-services.json
        script: |
          echo $GOOGLE_SERVICES_JSON | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json

      - name: Create .env.staging
        script: |
          echo $ENV_STAGING | base64 --decode > $CM_BUILD_DIR/.env.staging

      - name: Create dummy .env.prod
        script: |
          cp $CM_BUILD_DIR/.env.staging $CM_BUILD_DIR/.env.prod
          
      - name: Clean previous cache envied files
        script: dart run build_runner clean

      - name: Generate envied files
        script: dart run build_runner build --delete-conflicting-outputs

      - name: Get packages
        script: flutter pub get

      - name: Build staging APK
        script: flutter build apk --release --flavor staging

    artifacts:
      - build/**/outputs/apk/**/*.apk

    publishing:
      email:
        recipients:
          - kenkenku6@gmail.com
        notify:
          success: true
          failure: true